version: '3.8'

services:
  medbot:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
      - ~/.huggingface:/root/.huggingface
      - ~/.cache/huggingface:/root/.cache/huggingface

    environment:
      - HUGGINGFACE_TOKEN
    restart: "no"
