version: "3.9"

services:
  api:
    build: .
    container_name: medgemma-api
    ports:
      - "8000:8000"
    environment:
      DB_URL: "postgresql://postgres:postgres@localhost:5432/postgres"
      MODEL_PATH: "/models/dummy"
